# Generated by Django 5.2.10 on 2026-04-13 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_alter_aircraftgrease_id_alter_aircraftmodel_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Identificador Actividad')),
                ('name', models.CharField(max_length=255, verbose_name='Descripción de la Actividad')),
            ],
            options={
                'verbose_name': 'Actividad General',
                'verbose_name_plural': 'Actividades Generales',
            },
        ),
        migrations.CreateModel(
            name='BudgetFF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código FF')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Descripción FF')),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
            },
        ),
        migrations.CreateModel(
            name='BudgetFiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Año / Ejercicio')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Ejercicio Económico',
                'verbose_name_plural': 'Ejercicios Económicos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BudgetInc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código INC')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Inciso',
                'verbose_name_plural': 'Incisos',
            },
        ),
        migrations.CreateModel(
            name='BudgetIncisosAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Incisos Agrupados')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Incisos Agrupados',
                'verbose_name_plural': 'Incisos Agrupados',
            },
        ),
        migrations.CreateModel(
            name='BudgetPPAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código PPAI')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'PPAI',
                'verbose_name_plural': 'PPAIs',
            },
        ),
        migrations.CreateModel(
            name='BudgetPPInc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código PP-INC')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'PP-INC',
                'verbose_name_plural': 'PP-INCs',
            },
        ),
        migrations.CreateModel(
            name='BudgetPPPInc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código PPP-INC')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'PPP-INC',
                'verbose_name_plural': 'PPP-INCs',
            },
        ),
        migrations.CreateModel(
            name='BudgetPreInc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Pre-inc')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pre-inciso',
                'verbose_name_plural': 'Pre-incisos',
            },
        ),
        migrations.CreateModel(
            name='BudgetSubprog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código SUBPROG')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Descripción SUBPROG')),
            ],
            options={
                'verbose_name': 'Subprograma',
                'verbose_name_plural': 'Subprogramas',
            },
        ),
        migrations.CreateModel(
            name='BudgetCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('q2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('q3_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('q4_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetactivity', verbose_name='Actividad')),
                ('ff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetff', verbose_name='FF')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='budget.budgetfiscalyear', verbose_name='Ejercicio')),
                ('inc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetinc', verbose_name='INC')),
                ('incisos_agrupado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetincisosagrupado', verbose_name='Incisos')),
                ('ppai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetppai', verbose_name='PPAI')),
                ('pp_inc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetppinc', verbose_name='PP-INC')),
                ('ppp_inc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpppinc', verbose_name='PPP-INC')),
                ('pre_inc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpreinc', verbose_name='Pre-inc')),
                ('subprog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetsubprog', verbose_name='SUBPROG')),
            ],
            options={
                'verbose_name': 'Crédito Presupuestario',
                'verbose_name_plural': 'Créditos Presupuestarios',
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='core.unit')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budget.budgetcredit')),
            ],
            options={
                'unique_together': {('credit', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='BudgetExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=100)),
                ('commitment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commitment_date', models.DateField()),
                ('accrued_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('accrued_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='budget.budgetallocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
