# Generated by Django 5.2.10 on 2026-04-17 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('core', '0023_alter_aircraftgrease_id_alter_aircraftmodel_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetactivity',
            options={'verbose_name': 'Actividad General', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='budgetallocation',
            options={'verbose_name': 'Distribución de Crédito', 'verbose_name_plural': 'Distribuciones de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='budgetexecution',
            options={'verbose_name': 'Ejecución Presupuestaria', 'verbose_name_plural': 'Ejecuciones Presupuestarias'},
        ),
        migrations.AlterModelOptions(
            name='budgetff',
            options={'verbose_name': 'Fuente', 'verbose_name_plural': 'Fuentes'},
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Comprometido (Acumulado)'),
        ),
        migrations.AlterField(
            model_name='budgetactivity',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código ACT'),
        ),
        migrations.AlterField(
            model_name='budgetactivity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Actividad'),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Asignado (Techo)'),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budget.budgetcredit', verbose_name='Crédito Origen'),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='core.unit', verbose_name='Unidad Destino'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='accrued_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Devengado'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='accrued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devengado'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='budget.budgetallocation', verbose_name='Distribución / Techo'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='commitment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Comprometido'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='commitment_date',
            field=models.DateField(verbose_name='Fecha de Compromiso'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='reference_code',
            field=models.CharField(max_length=100, verbose_name='Nro. Expediente / Referencia'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='budgetinc',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='INC'),
        ),
        migrations.AlterField(
            model_name='budgetinc',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetincisosagrupado',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Incisos'),
        ),
        migrations.AlterField(
            model_name='budgetincisosagrupado',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetppai',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='PPAI'),
        ),
        migrations.AlterField(
            model_name='budgetppai',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetppinc',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='PP-INC'),
        ),
        migrations.AlterField(
            model_name='budgetppinc',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetpppinc',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='PPP-INC'),
        ),
        migrations.AlterField(
            model_name='budgetpppinc',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetpreinc',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Pre-inc'),
        ),
        migrations.AlterField(
            model_name='budgetpreinc',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcredit',
            unique_together={('fiscal_year', 'ff', 'subprog', 'actividad', 'inc', 'ppai')},
        ),
    ]
