# Generated by Django 5.2.10 on 2026-04-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budgetactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexecution',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Externo / Idempotencia'),
        ),
    ]
