# Generated by Django 5.2.10 on 2026-04-20 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgetprog_alter_budgetexecution_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='budget.budgetcredit', verbose_name='Crédito Origen'),
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='budget.budgetallocation', verbose_name='Distribución / Techo'),
        ),
    ]
