# Generated by Django 5.2.10 on 2026-04-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_budgetallocation_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetinc',
            options={'verbose_name': 'INCISO', 'verbose_name_plural': 'INCISOs'},
        ),
        migrations.AlterModelOptions(
            name='budgetincisosagrupado',
            options={'verbose_name': 'MONEDA', 'verbose_name_plural': 'MONEDAs'},
        ),
        migrations.AlterModelOptions(
            name='budgetppinc',
            options={'verbose_name': 'PARCIAL', 'verbose_name_plural': 'PARCIALes'},
        ),
        migrations.AlterModelOptions(
            name='budgetpppinc',
            options={'verbose_name': 'PPAL', 'verbose_name_plural': 'PPALs'},
        ),
        migrations.AlterModelOptions(
            name='budgetpreinc',
            options={'verbose_name': 'SUBPC', 'verbose_name_plural': 'SUBPCs'},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcredit',
            unique_together={('fiscal_year', 'ff', 'programa', 'subprog', 'inc', 'ppp_inc', 'pp_inc', 'pre_inc', 'incisos_agrupado')},
        ),
        migrations.AlterField(
            model_name='budgetcredit',
            name='inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetinc', verbose_name='INCISO'),
        ),
        migrations.AlterField(
            model_name='budgetcredit',
            name='incisos_agrupado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetincisosagrupado', verbose_name='MONEDA'),
        ),
        migrations.AlterField(
            model_name='budgetcredit',
            name='pp_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetppinc', verbose_name='PARCIAL'),
        ),
        migrations.AlterField(
            model_name='budgetcredit',
            name='ppp_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpppinc', verbose_name='PPAL'),
        ),
        migrations.AlterField(
            model_name='budgetcredit',
            name='pre_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpreinc', verbose_name='SUBPC'),
        ),
        migrations.AlterField(
            model_name='budgetinc',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código INCISO'),
        ),
        migrations.AlterField(
            model_name='budgetinc',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre INCISO'),
        ),
        migrations.AlterField(
            model_name='budgetincisosagrupado',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código MONEDA'),
        ),
        migrations.AlterField(
            model_name='budgetincisosagrupado',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre MONEDA'),
        ),
        migrations.AlterField(
            model_name='budgetppinc',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código PARCIAL'),
        ),
        migrations.AlterField(
            model_name='budgetppinc',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre PARCIAL'),
        ),
        migrations.AlterField(
            model_name='budgetpppinc',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código PPAL'),
        ),
        migrations.AlterField(
            model_name='budgetpppinc',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre PPAL'),
        ),
        migrations.AlterField(
            model_name='budgetpreinc',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código SUBPC'),
        ),
        migrations.AlterField(
            model_name='budgetpreinc',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre SUBPC'),
        ),
        migrations.RemoveField(
            model_name='budgetcredit',
            name='ppai',
        ),
    ]
