# Generated by Django 5.2.10 on 2026-04-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budgetinc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Clasificación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Descripción / Notas')),
            ],
            options={
                'verbose_name': 'Clasificación Personalizada',
                'verbose_name_plural': 'Clasificaciones Personalizadas',
            },
        ),
        migrations.DeleteModel(
            name='BudgetPPAI',
        ),
        migrations.AddField(
            model_name='budgetcredit',
            name='custom_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='budget.budgetclassification', verbose_name='Clasificación Especial'),
        ),
    ]
