# Generated by Django 5.2.10 on 2026-04-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budgetclassification_delete_budgetppai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre / Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Crédito',
                'verbose_name_plural': 'Tipos de Crédito',
            },
        ),
        migrations.AddField(
            model_name='budgetcredit',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='budget.budgetcredittype', verbose_name='Tipo de Crédito'),
        ),
    ]
