# Generated by Django 5.2.10 on 2026-04-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_budgetcredittype_budgetcredit_credit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCreditTypeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGN', 'Asignación'), ('UNASSIGN', 'Desasignación'), ('CHANGE', 'Cambio de Tipo')], max_length=10, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Motivo / Observaciones')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_logs', to='budget.budgetcredit', verbose_name='Crédito')),
                ('new_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_logs', to='budget.budgetcredittype', verbose_name='Tipo Nuevo')),
                ('previous_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unassigned_logs', to='budget.budgetcredittype', verbose_name='Tipo Anterior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registro de Cambio de Tipo',
                'verbose_name_plural': 'Registros de Cambios de Tipo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
