# Generated by Django 5.2.10 on 2026-04-29 13:58

from django.db import migrations, models

def migrate_custom_class_to_m2m(apps, schema_editor):
    BudgetCredit = apps.get_model('budget', 'BudgetCredit')
    for credit in BudgetCredit.objects.filter(custom_class__isnull=False):
        credit.custom_classes.add(credit.custom_class)

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_budgetcredittypelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcredit',
            name='custom_classes',
            field=models.ManyToManyField(blank=True, related_name='credits', to='budget.budgetclassification', verbose_name='Clasificaciones Especiales'),
        ),
        migrations.RunPython(migrate_custom_class_to_m2m, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='budgetcredit',
            name='custom_class',
        ),
    ]
