# Generated by Django 5.2.10 on 2026-04-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_remove_budgetcredit_custom_class_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcredit',
            unique_together={('fiscal_year', 'credit_type', 'ff', 'programa', 'subprog', 'inc', 'ppp_inc', 'pp_inc', 'pre_inc', 'incisos_agrupado')},
        ),
    ]
