# Generated by Django 5.2.10 on 2026-04-29 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_budgetallocation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCompensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T1')),
                ('q2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T2')),
                ('q3_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T3')),
                ('q4_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T4')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado (Listo para Ejecutar)'), ('RECHAZADO', 'Rechazado'), ('EJECUTADO', 'Ejecutado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetfiscalyear', verbose_name='Ejercicio')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetprog', verbose_name='Programa')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensaciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('source_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensaciones_salida', to='budget.budgetcredit', verbose_name='Crédito de Origen')),
                ('target_ff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetff', verbose_name='FF Destino')),
                ('target_inc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetinc', verbose_name='Inciso Destino')),
                ('target_incisos_agrupado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetincisosagrupado', verbose_name='Moneda Destino')),
                ('target_pp_inc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetppinc', verbose_name='Parcial Destino')),
                ('target_ppp_inc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpppinc', verbose_name='PPAL Destino')),
                ('target_pre_inc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpreinc', verbose_name='SubParcial Destino')),
                ('target_subprog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.budgetsubprog', verbose_name='Subprog Destino')),
            ],
            options={
                'verbose_name': 'Compensación de Partida',
                'verbose_name_plural': 'Compensaciones de Partidas',
            },
        ),
    ]
