# Generated by Django 5.2.10 on 2026-04-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_budgetcompensacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcompensacion',
            name='target_pp_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetppinc', verbose_name='Parcial Destino'),
        ),
        migrations.AlterField(
            model_name='budgetcompensacion',
            name='target_ppp_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpppinc', verbose_name='PPAL Destino'),
        ),
        migrations.AlterField(
            model_name='budgetcompensacion',
            name='target_pre_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgetpreinc', verbose_name='SubParcial Destino'),
        ),
    ]
