# Generated by Django 5.2.10 on 2026-04-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_budgetcompensacion_target_pp_inc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexecution',
            name='afecta_pg117',
            field=models.BooleanField(default=False, verbose_name='Afecta PG 117'),
        ),
        migrations.AddField(
            model_name='budgetexecution',
            name='numero_obra',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número de Obra'),
        ),
        migrations.AddField(
            model_name='budgetexecution',
            name='subcuenta',
            field=models.CharField(blank=True, default='51', max_length=2, null=True, verbose_name='Subcuenta (SC)'),
        ),
        migrations.AddField(
            model_name='budgetexecution',
            name='tipo_gasto',
            field=models.CharField(blank=True, choices=[('2', 'Gastos de Comida (JEMI)'), ('3', 'Mora en el Pago'), ('4', 'Mantenimiento Correctivo'), ('6', 'Viáticos Operativos'), ('7', 'Pasajes'), ('8', 'Viáticos con cargo'), ('9', 'I.C.D.')], max_length=1, null=True, verbose_name='Tipo de Gasto (TG)'),
        ),
        migrations.AddField(
            model_name='budgetprog',
            name='admin_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Administrador de Programa (3 chars)'),
        ),
    ]
