# Generated by Django 5.2.10 on 2026-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_budgetexecution_afecta_pg117_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='q1_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T1'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='q2_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T2'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='q3_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T3'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='q4_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto T4'),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Asignado (Techo Total)'),
        ),
    ]
