# Generated by Django 5.2.10 on 2026-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_budgetallocation_q1_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcredit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crédito Presupuestario', 'verbose_name_plural': 'Créditos Presupuestarios'},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcredit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetcredit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
