# Generated by Django 5.2.10 on 2026-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_alter_budgetcredit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcredit',
            name='custom_classes',
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='custom_classes',
            field=models.ManyToManyField(blank=True, related_name='allocations', to='budget.budgetclassification', verbose_name='Clasificaciones Especiales'),
        ),
    ]
