# Generated by Django 5.2.10 on 2026-05-08 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_remove_budgetcredit_custom_classes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCreditAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_old', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q2_old', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q3_old', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q4_old', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q1_new', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q2_new', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q3_new', models.DecimalField(decimal_places=2, max_digits=18)),
                ('q4_new', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField(verbose_name='Motivo del Ajuste')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='budget.budgetcredit', verbose_name='Crédito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Ajuste de Crédito',
                'verbose_name_plural': 'Ajustes de Crédito',
                'ordering': ['-timestamp'],
            },
        ),
    ]
