# Generated by Django 5.2.10 on 2026-05-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_budgetcreditadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre / Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gasto',
            },
        ),
        migrations.AlterField(
            model_name='budgetexecution',
            name='tipo_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.budgettipogasto', verbose_name='Tipo de Gasto (TG)'),
        ),
    ]
