# Generated by Django 5.2.10 on 2026-05-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_budgettipogasto_alter_budgetexecution_tipo_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetexecution',
            name='subcuenta',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Subcuenta (SC)'),
        ),
    ]
