# Generated by Django 5.2.10 on 2026-05-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_alter_budgetexecution_subcuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetclassification',
            options={'verbose_name': 'Proyecto / Plan de Gasto', 'verbose_name_plural': 'Proyectos / Planes de Gasto'},
        ),
        migrations.AddField(
            model_name='budgetclassification',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total proyectado para este objetivo.', max_digits=18, verbose_name='Meta / Presupuesto Estimado'),
        ),
        migrations.AlterField(
            model_name='budgetclassification',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Proyecto / Plan'),
        ),
    ]
