# Generated by Django 5.2.10 on 2026-08-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_reclassification_workflow'),
        ('core', '0032_alter_usersystempin_system_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetUnitBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Respaldo')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_backups', to='budget.budgetfiscalyear', verbose_name='Ejercicio')),
                ('pre_inc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_backups', to='budget.budgetpreinc', verbose_name='SUBPC')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_backups', to='core.unit', verbose_name='Unidad Destino')),
            ],
            options={
                'verbose_name': 'Respaldo de Unidad',
                'verbose_name_plural': 'Respaldos de Unidades',
                'unique_together': {('fiscal_year', 'unit', 'pre_inc')},
            },
        ),
    ]
