# Generated by Django 5.2.10 on 2026-08-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_budgetunitbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcredit',
            name='pre_inc_display',
            field=models.ForeignKey(blank=True, help_text='Si se completa, este crédito aparecerá bajo este subparcial en la tabla consolidada, en lugar de su SUBPC original. Dejar vacío para usar el SUBPC original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_display', to='budget.budgetpreinc', verbose_name='SUBPC Visual (reclasificación)'),
        ),
    ]
