# Generated by Django 5.2.10 on 2026-08-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_add_pre_inc_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCreditSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Reclasificado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='budget.budgetcredit', verbose_name='Crédito')),
                ('pre_inc_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_splits', to='budget.budgetpreinc', verbose_name='SUBPC Destino')),
            ],
            options={
                'verbose_name': 'Reclasificación Parcial',
                'verbose_name_plural': 'Reclasificaciones Parciales',
                'ordering': ['pre_inc_destino__code'],
            },
        ),
    ]
