# Generated by Django 5.2.10 on 2026-08-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_add_budget_credit_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetFoxtrotCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Techo Foxtrot')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foxtrot_ceilings', to='budget.budgetfiscalyear')),
                ('pre_inc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foxtrot_ceilings', to='budget.budgetpreinc')),
            ],
            options={
                'verbose_name': 'Techo Foxtrot',
                'verbose_name_plural': 'Techos Foxtrot',
                'unique_together': {('fiscal_year', 'pre_inc')},
            },
        ),
    ]
