# Generated by Django 5.2.10 on 2026-05-31 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0003_update_year_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderprocess',
            options={'ordering': ['-year', 'unit__name', '-opening_date', 'process_number'], 'verbose_name': 'Proceso licitatorio', 'verbose_name_plural': 'Procesos licitatorios'},
        ),
    ]
