# Generated by Django 5.2.10 on 2026-06-29 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0006_foreign_tenders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField(verbose_name='Numero de etapa')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de etapa')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('OMITIDA', 'Omitida')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('estimated_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio real')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin real')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tender_stages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='licitaciones.tenderprocess', verbose_name='Licitacion')),
            ],
            options={
                'verbose_name': 'Etapa de licitacion',
                'verbose_name_plural': 'Etapas de licitacion',
                'ordering': ['stage_number'],
                'unique_together': {('tender', 'stage_number')},
            },
        ),
    ]
