# Generated by Django 5.2.10 on 2026-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0011_foreign_tender_delivery_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntenderprocess',
            name='oca_expiration',
            field=models.CharField(blank=True, help_text="Admite una fecha o una aclaracion, por ejemplo 'No aplica'.", max_length=150, verbose_name='Fecha de vencimiento'),
        ),
    ]
