# Generated by Django 5.2.10 on 2026-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0012_alter_foreigntenderprocess_oca_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigntenderprocess',
            name='sp_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de la SP'),
        ),
        migrations.AddField(
            model_name='foreigntenderprocess',
            name='sp_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión de la SP'),
        ),
    ]
