# Generated by Django 5.2.10 on 2026-08-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0013_foreigntenderprocess_sp_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigntenderprocess',
            name='sp',
        ),
        migrations.RemoveField(
            model_name='foreigntenderprocess',
            name='sp_amount',
        ),
        migrations.RemoveField(
            model_name='foreigntenderprocess',
            name='sp_issue_date',
        ),
        migrations.CreateModel(
            name='ForeignProvisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_number', models.CharField(max_length=40, verbose_name='Nro. SP')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto SP')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_requests', to='licitaciones.foreigntenderpurchaseorder', verbose_name='Orden de Compra / OCA')),
            ],
            options={
                'verbose_name': 'Solicitud de provision',
                'verbose_name_plural': 'Solicitudes de provision',
                'ordering': ['issue_date', 'sp_number'],
            },
        ),
    ]
