# Generated by Django 5.2.10 on 2026-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0014_remove_foreigntenderprocess_sp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreigntenderpurchaseorder',
            options={'ordering': ['expiration_date', 'order_number'], 'verbose_name': 'Orden de compra exterior', 'verbose_name_plural': 'Ordenes de compra exteriores'},
        ),
        migrations.RemoveField(
            model_name='foreigntenderprocess',
            name='delivery_term_day_type',
        ),
        migrations.RemoveField(
            model_name='foreigntenderprocess',
            name='delivery_term_days',
        ),
        migrations.RemoveField(
            model_name='foreigntenderprocess',
            name='oca_expiration',
        ),
        migrations.AddField(
            model_name='foreigntenderpurchaseorder',
            name='delivery_term_day_type',
            field=models.CharField(blank=True, choices=[('CORRIDOS', 'Dias corridos'), ('HABILES', 'Dias habiles (lunes a viernes)')], max_length=10, verbose_name='Tipo de dias del plazo de entrega'),
        ),
        migrations.AddField(
            model_name='foreigntenderpurchaseorder',
            name='delivery_term_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de dias del plazo de entrega'),
        ),
        migrations.AddField(
            model_name='foreigntenderpurchaseorder',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
