# Generated by Django 5.2.10 on 2026-08-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0015_alter_foreigntenderpurchaseorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigntenderpurchaseorder',
            name='delivery_term_day_type',
        ),
        migrations.RemoveField(
            model_name='foreigntenderpurchaseorder',
            name='delivery_term_days',
        ),
    ]
