# Generated by Django 5.2.10 on 2026-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0016_remove_foreigntenderpurchaseorder_delivery_term_day_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigntenderpurchaseorder',
            name='order_type',
            field=models.CharField(choices=[('OC', 'Orden de Compra (OC)'), ('OCA', 'Orden de Compra Abierta (OCA)')], default='OC', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='foreigntenderpurchaseorder',
            name='order_number',
            field=models.CharField(max_length=40, verbose_name='Número de orden'),
        ),
    ]
