# Generated by Django 5.2.10 on 2026-08-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0017_foreigntenderpurchaseorder_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignprovisionrequest',
            name='saimb_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='SAIMB Nro.'),
        ),
        migrations.AddField(
            model_name='foreigntenderpurchaseorder',
            name='saimb_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='SAIMB Nro.'),
        ),
    ]
