# Generated by Django 5.2.10 on 2026-08-05 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0018_foreignprovisionrequest_saimb_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='foreigntenderprocess',
            name='unique_foreign_tender_year_number',
        ),
        migrations.AlterUniqueTogether(
            name='tenderprocess',
            unique_together={('year', 'process_type', 'process_number')},
        ),
        migrations.AddConstraint(
            model_name='foreigntenderprocess',
            constraint=models.UniqueConstraint(fields=('year', 'process_type', 'process_number'), name='unique_foreign_tender_year_type_number'),
        ),
    ]
