# Generated by Django 5.2.10 on 2026-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0019_remove_foreigntenderprocess_unique_foreign_tender_year_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignprovisionrequest',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
