# Generated by Django 5.2.10 on 2026-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0020_foreignprovisionrequest_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignprovisionrequest',
            name='received',
            field=models.BooleanField(blank=True, null=True, verbose_name='Recibido'),
        ),
    ]
