# Generated by Django 5.2.10 on 2026-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0021_foreignprovisionrequest_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntenderprocess',
            name='expediente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Objeto / Expediente'),
        ),
    ]
