# Generated by Django 5.2.10 on 2026-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0022_alter_foreigntenderprocess_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigntenderpurchaseorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=150, verbose_name='Proveedor'),
        ),
    ]
