# Generated by Django 5.2.10 on 2026-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0023_foreigntenderpurchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderprocess',
            name='ipp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IPP'),
        ),
    ]
