# Generated by Django 5.2.10 on 2026-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0025_alter_tenderprocess_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderprocess',
            name='classification',
            field=models.CharField(blank=True, choices=[('', 'Sin clasificar'), ('REPUESTO', 'Repuesto'), ('SUPERVIVENCIA', 'Supervivencia'), ('GRASAS_LUBRICANTES', 'Grasas y Lubricantes'), ('REPUESTOS_FONDEF', 'Repuestos / FONDEF')], default='', max_length=100, verbose_name='Clasificacion'),
        ),
    ]
