# Generated by Django 5.2.10 on 2026-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0027_alter_tenderprocess_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderprocess',
            name='status',
            field=models.CharField(choices=[('PUBLICADO', 'Publicado'), ('EN_APERTURA', 'En apertura'), ('EN_EVALUACION', 'En evaluacion'), ('PREADJUDICADO_DISPONIBLE', 'Preadjudicado / Disponible para adjudicar'), ('ADJUDICADO', 'Adjudicado'), ('FRACASADO', 'Fracasado'), ('DESIERTO', 'Desierto'), ('DEJADO_SIN_EFECTO', 'Dejado sin efecto')], default='PUBLICADO', max_length=30, verbose_name='Estado'),
        ),
    ]
