# Generated by Django 6.0.2 on 2026-02-24 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Modelo de Aeronave')),
                ('total_aircraft', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Aeronaves')),
                ('is_active', models.BooleanField(default=True, verbose_name='Operativa (Activa)')),
            ],
            options={
                'verbose_name': 'Modelo de Aeronave',
                'verbose_name_plural': 'Modelos de Aeronaves',
            },
        ),
        migrations.CreateModel(
            name='GreaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_designation', models.CharField(max_length=100, unique=True, verbose_name='Designación Técnica')),
                ('specification', models.CharField(max_length=100, verbose_name='Especificación o Norma (MIL/NATO/OEM)')),
                ('packaging', models.CharField(max_length=50, verbose_name='Presentación (kg, cartucho, lata)')),
                ('shelf_life_months', models.PositiveIntegerField(verbose_name='Vida Útil Total (Meses)')),
                ('recertification_allowed', models.BooleanField(default=False, verbose_name='Permite Re-certificación')),
            ],
            options={
                'verbose_name': 'Tipo de Grasa',
                'verbose_name_plural': 'Tipos de Grasas',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Unidad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], max_length=20, verbose_name='Tipo de Período')),
                ('period_start_date', models.DateField(verbose_name='Fecha de Inicio del Plan')),
                ('planned_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas de Vuelo Planificadas')),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_plans', to='core.aircraftmodel', verbose_name='Modelo de Aeronave')),
            ],
            options={
                'verbose_name': 'Plan de Vuelo',
                'verbose_name_plural': 'Planes de Vuelo',
            },
        ),
        migrations.CreateModel(
            name='GreaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Número de Lote')),
                ('manufacturing_date', models.DateField(verbose_name='Fecha de Fabricación')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Inicial')),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Disponible')),
                ('storage_location', models.CharField(max_length=100, verbose_name='Ubicación (Almacén/Unidad)')),
                ('status', models.CharField(choices=[('SERVICEABLE', 'Retesteable'), ('NEAR_EXPIRATION', 'Próximo a Vencer'), ('EXPIRED', 'Vencido'), ('PENDING_RECERTIFICATION', 'Pendiente Re-certificación')], default='SERVICEABLE', max_length=30, verbose_name='Estado')),
                ('grease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.greasetype', verbose_name='Tipo de Grasa')),
            ],
            options={
                'verbose_name': 'Lote de Grasa',
                'verbose_name_plural': 'Lotes de Grasas',
                'unique_together': {('grease_type', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INCOMING', 'Ingreso inicial'), ('CONSUMPTION', 'Consumo operativo'), ('ADJUSTMENT', 'Ajuste de inventario/Auditoría')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity_changed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Alterada (+ o -)')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Movimiento')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia (Nro Remito / Plan Vuelo)')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo / Observaciones')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.greasebatch', verbose_name='Lote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock (Auditoría)',
                'verbose_name_plural': 'Movimientos de Stock (Auditoría)',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='core.unit', verbose_name='Unidad / Escuadra'),
        ),
        migrations.CreateModel(
            name='AircraftGrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_consumption_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Consumo por Hora de Vuelo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas (Punto de aplicación)')),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grease_associations', to='core.aircraftmodel', verbose_name='Modelo de Aeronave')),
                ('grease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_associations', to='core.greasetype', verbose_name='Tipo de Grasa')),
            ],
            options={
                'verbose_name': 'Asociación Aeronave-Grasa',
                'verbose_name_plural': 'Asociaciones Aeronave-Grasa',
                'unique_together': {('aircraft_model', 'grease_type')},
            },
        ),
    ]
