# Generated by Django 6.0.2 on 2026-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aircraftmodel_greasetype_unit_flightplan_greasebatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greasetype',
            options={'verbose_name': 'Tipo de Grasa / Aceite', 'verbose_name_plural': 'Tipos de Grasas / Aceites'},
        ),
        migrations.RemoveField(
            model_name='greasetype',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='greasetype',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='greasetype',
            name='technical_designation',
        ),
        migrations.AddField(
            model_name='greasetype',
            name='nato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NATO'),
        ),
        migrations.AddField(
            model_name='greasetype',
            name='nne_nsn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N.N.E. / N.S.N.'),
        ),
        migrations.AddField(
            model_name='greasetype',
            name='nomenclatura',
            field=models.CharField(default='Migrating', max_length=150, verbose_name='NOMENCLATURA'),
        ),
        migrations.AddField(
            model_name='greasetype',
            name='normas_mil_otras',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NORMAS MIL / OTRAS'),
        ),
        migrations.AddField(
            model_name='greasetype',
            name='presentacion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='PRESENTACIÓN'),
        ),
        migrations.AddField(
            model_name='greasetype',
            name='sibys',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SIBYS'),
        ),
        migrations.AddField(
            model_name='greasetype',
            name='unidad',
            field=models.CharField(default='LT', max_length=50, verbose_name='UNIDAD'),
        ),
    ]
