# Generated by Django 6.0.2 on 2026-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_greasetype_options_remove_greasetype_packaging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greasetype',
            name='nomenclatura',
            field=models.CharField(max_length=150, unique=True, verbose_name='NOMENCLATURA'),
        ),
        migrations.AlterField(
            model_name='greasetype',
            name='presentacion',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PRESENTACIÓN'),
        ),
        migrations.AlterField(
            model_name='greasetype',
            name='unidad',
            field=models.CharField(max_length=50, verbose_name='UNIDAD'),
        ),
    ]
