# Generated by Django 6.0.2 on 2026-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_greasetype_nomenclatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightplan',
            options={'verbose_name': 'Plan de Empleo', 'verbose_name_plural': 'Planes de Empleo'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia (Nro Remito / Plan Empleo)'),
        ),
    ]
