# Generated by Django 6.0.2 on 2026-03-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_flightplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greasebatch',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo pagado por UNIDAD de medida (1 Kg o 1 L) para este lote específico.', max_digits=12, null=True, verbose_name='Costo Unitario Real ($)'),
        ),
        migrations.CreateModel(
            name='GreaseReferencePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de la Presentación ($)')),
                ('presentation_quantity', models.DecimalField(decimal_places=2, help_text='Ej: Para una lata de 5kg que vale $5000, ingrese 5. El costo unitario será $1000/kg.', max_digits=10, verbose_name='Cantidad en la Presentación (Kg/L)')),
                ('supplier', models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor (Opcional)')),
                ('date_recorded', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('grease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_prices', to='core.greasetype', verbose_name='Tipo de Grasa')),
            ],
            options={
                'verbose_name': 'Precio de Referencia',
                'verbose_name_plural': 'Precios de Referencia',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
