# Generated by Django 6.0.2 on 2026-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_greasebatch_unit_price_greasereferenceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greasebatch',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo real calculado por unidad (Kg/L).', max_digits=12, null=True, verbose_name='Costo Unitario Real ($)'),
        ),
    ]
