# Generated by Django 6.0.2 on 2026-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_greasebatch_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greasebatch',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Costo real calculado por unidad (Kg/L).', max_digits=14, null=True, verbose_name='Costo Unitario Real ($)'),
        ),
    ]
