# Generated by Django 6.0.2 on 2026-03-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_greasebatch_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightplan',
            name='period_end_date',
            field=models.DateField(blank=True, help_text='Déjelo en blanco si escoge mensual, trimestral o anual para autocalcular.', null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='period_type',
            field=models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual'), ('CUSTOM', 'Libre / Personalizado')], max_length=20, verbose_name='Tipo de Período'),
        ),
    ]
