# Generated by Django 6.0.2 on 2026-03-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_measurementunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='greasebatch',
            name='can_be_retested',
            field=models.BooleanField(default=True, help_text='Indica si este lote puede ser sometido a un nuevo retesteo cuando venza.', verbose_name='¿Admite retesteo futuro?'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('INCOMING', 'Ingreso inicial'), ('CONSUMPTION', 'Consumo operativo'), ('ADJUSTMENT', 'Ajuste de inventario/Auditoría'), ('RETEST', 'Retesteo / Extensión de Vencimiento')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
    ]
