# Generated by Django 5.2.10 on 2026-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aircraftgrease_id_alter_aircraftmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greasereferenceprice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está marcado, este precio se incluirá en el cálculo del costo promedio.', verbose_name='Utilizar para Promedio'),
        ),
    ]
