# Generated by Django 5.2.10 on 2026-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_greasereferenceprice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='greasetype',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Punto de pedido. El sistema enviará alertas si el stock cae por debajo de esta cantidad.', max_digits=10, verbose_name='Stock Mínimo Permanente'),
        ),
    ]
