# Generated by Django 5.2.10 on 2026-03-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_greasetype_minimum_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='greasetype',
            unique_together={('nomenclatura', 'presentacion', 'normas_mil_otras')},
        ),
    ]
