# Generated by Django 5.2.10 on 2026-03-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_greasetype_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Asignar una unidad para restringir al usuario a consumos únicamente de esta ubicación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.unit', verbose_name='Unidad / Escuadrilla Asignada'),
        ),
    ]
