# Generated by Django 5.2.10 on 2026-03-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_unit'),
    ]

    operations = [
    ]
