# Generated by Django 5.2.10 on 2026-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_unit_to_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greasebatch',
            name='status',
            field=models.CharField(choices=[('SERVICEABLE', 'Retesteable'), ('NEAR_EXPIRATION', 'Próximo a Vencer'), ('EXPIRED', 'Vencido'), ('PENDING_RETEST', 'Retesteando...')], default='SERVICEABLE', max_length=30, verbose_name='Estado'),
        ),
    ]
