# Generated by Django 5.2.10 on 2026-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_greasebatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='greasebatch',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='¿Archivado (Historial)?'),
        ),
    ]
