# Generated by Django 5.2.10 on 2026-03-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_greasebatch_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greasebatch',
            options={'verbose_name': 'Casamata', 'verbose_name_plural': 'Casamatas'},
        ),
        migrations.AlterUniqueTogether(
            name='greasebatch',
            unique_together={('grease_type', 'batch_number', 'storage_location')},
        ),
    ]
