# Generated by Django 5.2.10 on 2026-03-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_greasebatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Requerida')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Compra'), ('ORDERED', 'En proceso de Compra'), ('DELIVERED', 'Recibido / Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('grease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.greasetype', verbose_name='Tipo de Grasa')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
            ],
            options={
                'verbose_name': 'Requerimiento de Adquisición',
                'verbose_name_plural': 'Requerimientos de Adquisición',
                'ordering': ['-request_date'],
            },
        ),
    ]
