# Generated by Django 5.2.10 on 2026-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_procurementrequirement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='greasetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='greasebatch',
            name='container_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número de envases/latas en este lote', null=True, verbose_name='Cantidad de Envases'),
        ),
        migrations.AddField(
            model_name='greasebatch',
            name='container_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 5 para un envase de 5 Kg', max_digits=10, null=True, verbose_name='Cantidad por Envase'),
        ),
        migrations.AlterField(
            model_name='greasebatch',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Total Inicial'),
        ),
        migrations.RemoveField(
            model_name='greasetype',
            name='presentacion',
        ),
    ]
