# Generated by Django 5.2.10 on 2026-04-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_aircraftgrease_id_alter_aircraftmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='component_code',
            field=models.CharField(blank=True, help_text='Ej: UUUUUU', max_length=6, null=True, verbose_name='Código Unidad Componente (6 chars)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='ot_code',
            field=models.CharField(blank=True, help_text='Ej: 001', max_length=3, null=True, verbose_name='Organismo Técnico (OT)'),
        ),
    ]
