# Generated by Django 5.2.10 on 2026-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_unit_component_code_unit_ot_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_pin',
            field=models.CharField(blank=True, help_text='PIN de 4 dígitos para acceso a sistemas sensibles.', max_length=128, null=True, verbose_name='PIN de Seguridad (Hashed)'),
        ),
    ]
