# Generated by Django 5.2.10 on 2026-05-13 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_security_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='security_pin',
        ),
        migrations.CreateModel(
            name='UserSystemPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(choices=[('sgmg', 'Materias Grasas (SGMG)'), ('sigera', 'Ropa de Trabajo (SIGERA)'), ('sgp', 'Presupuesto (SGP)')], max_length=20, verbose_name='Sistema')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='PIN de Seguridad (Hashed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso por PIN a Sistema',
                'verbose_name_plural': 'Accesos por PIN a Sistemas',
                'unique_together': {('user', 'system_code')},
            },
        ),
    ]
