# Generated by Django 5.2.10 on 2026-05-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_licitaciones_pin_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greasebatch',
            name='status',
            field=models.CharField(choices=[('SERVICEABLE', 'Retesteable'), ('NEAR_EXPIRATION', 'Próximo a Vencer'), ('EXPIRED', 'Vencido'), ('PENDING_RETEST', 'Retesteando...'), ('REJECTED', 'Rechazado en Retesteo')], default='SERVICEABLE', max_length=30, verbose_name='Estado'),
        ),
    ]
