# Generated by Django 5.2.10 on 2026-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_procurement_delete_pin_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystempin',
            name='system_code',
            field=models.CharField(choices=[('sgmg', 'Materias Grasas (SGMG)'), ('sigera', 'Ropa de Trabajo (SIGERA)'), ('sgp', 'Presupuesto (SGP)'), ('licitaciones', 'Licitaciones'), ('supervivencia', 'Supervivencia / Pirotecnia'), ('supervivencia_admin', 'Supervivencia / Administracion'), ('procurement_delete', 'Borrado de Compras'), ('sigera_delete', 'Borrado de Ropa (SIGERA)')], max_length=20, verbose_name='Sistema'),
        ),
    ]
