# Generated by Django 5.2.10 on 2026-09-24 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_usersystempin_system_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUnitResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(choices=[('sigera', 'Ropa de Trabajo (SIGERA)'), ('sgmg', 'Materias Grasas (SGMG)'), ('supervivencia', 'Supervivencia / Pirotecnia'), ('sgp', 'Presupuesto (SGP)'), ('licitaciones', 'Licitaciones')], max_length=30, verbose_name='Sistema')),
                ('rank_and_name', models.CharField(help_text='Ej: Cap. Fragata López Juan', max_length=150, verbose_name='Grado, Nombre y Apellido')),
                ('role', models.CharField(choices=[('titular', 'Responsable Titular'), ('suplente', 'Responsable Suplente'), ('operador', 'Encargado de Carga / Operador'), ('control', 'Control / Supervisión')], default='titular', max_length=20, verbose_name='Rol / Función')),
                ('phone', models.CharField(blank=True, help_text='Ej: Int. 4201 / Cel. 291-...', max_length=50, null=True, verbose_name='Teléfono / Interno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones / Novedades')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_responsibles', to='core.unit', verbose_name='Unidad / Destino')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_system_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema (Opcional)')),
            ],
            options={
                'verbose_name': 'Responsable por Sistema y Destino',
                'verbose_name_plural': 'Responsables por Sistema y Destino',
                'ordering': ['unit__name', 'system_code', 'role', 'rank_and_name'],
            },
        ),
    ]
