# Generated by Django 5.2.10 on 2026-04-02 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_remove_presentacion_add_container_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Ej: S, M, L, XL, 42, 44', max_length=50, verbose_name='Talle')),
            ],
            options={
                'verbose_name': 'Talle de Prenda',
                'verbose_name_plural': 'Talles de Prendas',
            },
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Mameluco de Vuelo, Borceguíes', max_length=150, verbose_name='Nombre de la Prenda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nato_stock_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N.N.E. / N.S.N.')),
                ('shelf_life_months', models.PositiveIntegerField(help_text='Tiempo estimado de uso antes de requerir reemplazo', verbose_name='Vida Útil Teórica (Meses)')),
            ],
            options={
                'verbose_name': 'Tipo de Prenda',
                'verbose_name_plural': 'Tipos de Prendas',
            },
        ),
        migrations.CreateModel(
            name='ClothingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.DateField(verbose_name='Fecha de Recepción')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='Cantidad Recibida Inicial')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Cantidad Disponible en Pañol')),
                ('provider', models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor')),
                ('purchase_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra / Remito / Factura')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Unitario ($)')),
                ('clothing_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='sigera.clothingsize', verbose_name='Prenda y Talle')),
            ],
            options={
                'verbose_name': 'Lote/Ingreso de Ropa',
                'verbose_name_plural': 'Lotes/Ingresos de Ropa',
                'ordering': ['-reception_date'],
            },
        ),
        migrations.AddField(
            model_name='clothingsize',
            name='clothing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='sigera.clothingtype', verbose_name='Prenda'),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI / NI')),
                ('rank', models.CharField(choices=[('OFICIAL', 'Oficial'), ('SUBOFICIAL', 'Suboficial'), ('MARINERO', 'Marinero'), ('CIVIL', 'Civil')], max_length=20, verbose_name='Jerarquía/Rango')),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='Unidad Asignada')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad Entregada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('returned', models.BooleanField(default=False, verbose_name='¿Devuelto al Pañol?')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Entregado Por')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='sigera.clothingbatch', verbose_name='Del Ingreso (Lote)')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sigera.personnel', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Entrega de Ropa',
                'verbose_name_plural': 'Entregas de Ropa',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='clothingsize',
            unique_together={('clothing_type', 'size')},
        ),
    ]
