# Generated by Django 5.2.10 on 2026-04-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula de Revista'),
        ),
    ]
