# Generated by Django 5.2.10 on 2026-04-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0002_alter_personnel_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.CharField(choices=[('CAPITAN_NAVIO', 'Capitán de Navío'), ('CAPITAN_FRAGATA', 'Capitán de Fragata'), ('CAPITAN_CORBETA', 'Capitán de Corbeta'), ('TENIENTE_NAVIO', 'Teniente de Navío'), ('TENIENTE_FRAGATA', 'Teniente de Fragata'), ('TENIENTE_CORBETA', 'Teniente de Corbeta'), ('GUARDIAMARINA', 'Guardiamarina'), ('SUBOFICIAL_MAYOR', 'Suboficial Mayor'), ('SUBOFICIAL_PRINCIPAL', 'Suboficial Principal'), ('SUBOFICIAL_PRIMERO', 'Suboficial Primero'), ('SUBOFICIAL_SEGUNDO', 'Suboficial Segundo'), ('CABO_PRINCIPAL', 'Cabo Principal'), ('CABO_PRIMERO', 'Cabo Primero'), ('CABO_SEGUNDO', 'Cabo Segundo'), ('MARINERO_PRIMERO', 'Marinero Primero'), ('MARINERO_SEGUNDO', 'Marinero Segundo'), ('AGENTE_CIVIL', 'Agente Civil')], max_length=20, verbose_name='Jerarquía/Rango'),
        ),
    ]
