# Generated by Django 5.2.10 on 2026-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0003_alter_personnel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingtype',
            name='must_be_returned',
            field=models.BooleanField(default=True, help_text='Indica si esta prenda debe ser devuelta al pañol cuando el personal la cese de usar.', verbose_name='¿Debe ser devuelta?'),
        ),
    ]
