# Generated by Django 5.2.10 on 2026-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0004_clothingtype_must_be_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Suficiente, OK, Crítico', max_length=50, verbose_name='Nombre de la Categoría')),
                ('min_quantity', models.PositiveIntegerField(help_text='Incluye esta cantidad', verbose_name='Cantidad Mínima')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Hasta esta cantidad (deja vacío para ilimitado)', null=True, verbose_name='Cantidad Máxima')),
                ('color', models.CharField(choices=[('danger', 'Rojo (Peligro)'), ('warning', 'Naranja (Advertencia)'), ('info', 'Azul (Información)'), ('success', 'Verde (Éxito)'), ('secondary', 'Gris (Secundario)')], default='secondary', max_length=20, verbose_name='Color del Badge')),
                ('icon', models.CharField(default='fa-circle', help_text='Ej: fa-circle-check, fa-triangle-exclamation', max_length=50, verbose_name='Ícono de FontAwesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de Aparición')),
            ],
            options={
                'verbose_name': 'Umbral de Stock',
                'verbose_name_plural': 'Umbrales de Stock',
                'ordering': ['order'],
            },
        ),
    ]
