# Generated by Django 5.2.10 on 2026-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0008_clothingassignment_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingbatch',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Ej: Estante 4, Pañol Central', max_length=150, null=True, verbose_name='Depósito / Ubicación'),
        ),
    ]
