# Generated by Django 5.2.10 on 2026-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0009_clothingbatch_storage_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clothingsize',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clothingsize',
            name='size_system',
            field=models.CharField(blank=True, default='', help_text='Ej: Europeo, Americano, Nacional', max_length=60, verbose_name='Sistema de talles'),
        ),
        migrations.AlterUniqueTogether(
            name='clothingsize',
            unique_together={('clothing_type', 'size_system', 'size')},
        ),
    ]
