# Generated by Django 5.2.10 on 2026-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigera', '0010_alter_clothingsize_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personnelclothingmeasure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='personnelclothingmeasure',
            name='size_system',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Sistema de talles'),
        ),
        migrations.AlterUniqueTogether(
            name='personnelclothingmeasure',
            unique_together={('personnel', 'clothing_type', 'size_system')},
        ),
    ]
