# Generated by Django 5.2.10 on 2026-06-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0015_catalog_part_number_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pyrotechnicassignment',
            new_name='supervivenc_is_acti_d81d84_idx',
            old_name='superviven_is_acti_8d35e6_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicassignment',
            new_name='supervivenc_install_3e2b53_idx',
            old_name='superviven_install_1e6cb9_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicassignment',
            new_name='supervivenc_removed_b0546f_idx',
            old_name='superviven_removed_7d6804_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicmovement',
            new_name='supervivenc_movemen_d8d170_idx',
            old_name='superviven_movemen_b54b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicmovement',
            new_name='supervivenc_movemen_e633c4_idx',
            old_name='superviven_movemen_0e476d_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicmovement',
            new_name='supervivenc_physica_a62e54_idx',
            old_name='superviven_physica_90e3d7_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicmovement',
            new_name='supervivenc_medium__8ed557_idx',
            old_name='superviven_medium__5f02e7_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicphysicalitem',
            new_name='supervivenc_expirat_fe6341_idx',
            old_name='superviven_expirat_d47f43_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicphysicalitem',
            new_name='supervivenc_conditi_6ff5c9_idx',
            old_name='superviven_conditi_447c6e_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicphysicalitem',
            new_name='supervivenc_operati_9aebda_idx',
            old_name='superviven_operati_c5d24d_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicphysicalitem',
            new_name='supervivenc_is_acti_c29b04_idx',
            old_name='superviven_is_acti_24c7d1_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicphysicalitem',
            new_name='supervivenc_current_1d4325_idx',
            old_name='superviven_current_f110c0_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicrequirement',
            new_name='supervivenc_year_697f48_idx',
            old_name='superviven_year_48752d_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicrequirement',
            new_name='supervivenc_status_cd4c4a_idx',
            old_name='superviven_status_49b422_idx',
        ),
        migrations.RenameIndex(
            model_name='pyrotechnicrequirement',
            new_name='supervivenc_is_acti_868d67_idx',
            old_name='superviven_is_acti_39246e_idx',
        ),
    ]
