# Generated by Django 5.2.10 on 2026-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_procurement_delete_pin_system'),
        ('supervivencia', '0016_rename_superviven_is_acti_8d35e6_idx_supervivenc_is_acti_d81d84_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyrotechnicstoragelocation',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Destino'),
        ),
        migrations.AddConstraint(
            model_name='pyrotechnicstoragelocation',
            constraint=models.UniqueConstraint(fields=('code', 'name', 'location_type', 'unit'), name='unique_storage_location_combination'),
        ),
    ]
