# Generated by Django 5.2.10 on 2026-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_procurement_delete_pin_system'),
        ('supervivencia', '0019_drop_legacy_part_number_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pyrotechnicstoragelocation',
            name='unique_storage_location_combination',
        ),
        migrations.RemoveField(
            model_name='pyrotechnicstoragelocation',
            name='location_type',
        ),
        migrations.AlterField(
            model_name='pyrotechnicstoragelocation',
            name='name',
            field=models.CharField(choices=[('POLVORIN', 'Polvorin'), ('PANOL', 'Pañol'), ('DEPOSITO', 'Deposito'), ('TALLER', 'Taller'), ('OTRO', 'Otro')], default='DEPOSITO', max_length=150, verbose_name='Ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='pyrotechnicstoragelocation',
            constraint=models.UniqueConstraint(fields=('code', 'name', 'unit'), name='unique_storage_location_combination'),
        ),
    ]
