# Generated by Django 5.2.10 on 2026-08-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0020_remove_pyrotechnicstoragelocation_unique_storage_location_combination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Clasificacion')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Clasificacion de elemento',
                'verbose_name_plural': 'Clasificaciones de elementos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='pyrotechniccatalogitem',
            name='system',
            field=models.CharField(max_length=150, verbose_name='Sistema (Antiguo)'),
        ),
        migrations.CreateModel(
            name='ItemSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sistema')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='supervivencia.itemclassification', verbose_name='Clasificacion')),
            ],
            options={
                'verbose_name': 'Sistema de elemento',
                'verbose_name_plural': 'Sistemas de elementos',
                'ordering': ['classification__name', 'name'],
                'unique_together': {('classification', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pyrotechniccatalogitem',
            name='system_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supervivencia.itemsystem', verbose_name='Sistema'),
        ),
    ]
