# Generated by Django 5.2.10 on 2026-08-27 13:36

from django.db import migrations

def migrate_system_data(apps, schema_editor):
    PyrotechnicCatalogItem = apps.get_model('supervivencia', 'PyrotechnicCatalogItem')
    ItemClassification = apps.get_model('supervivencia', 'ItemClassification')
    ItemSystem = apps.get_model('supervivencia', 'ItemSystem')

    default_classification, _ = ItemClassification.objects.get_or_create(
        name="GENERAL",
        defaults={"description": "Clasificación generada automáticamente durante migración"}
    )

    for item in PyrotechnicCatalogItem.objects.all():
        system_name = item.system.strip().upper() if item.system else "S/D"
        
        system_obj, _ = ItemSystem.objects.get_or_create(
            name=system_name,
            classification=default_classification
        )
        
        item.system_fk = system_obj
        item.save(update_fields=['system_fk'])

def reverse_migrate_system_data(apps, schema_editor):
    PyrotechnicCatalogItem = apps.get_model('supervivencia', 'PyrotechnicCatalogItem')
    for item in PyrotechnicCatalogItem.objects.all():
        if item.system_fk:
            item.system = item.system_fk.name
            item.save(update_fields=['system'])

class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0021_itemclassification_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_system_data, reverse_migrate_system_data),
    ]
