# Generated by Django 5.2.10 on 2026-08-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0022_migrate_system_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyrotechniccatalogitem',
            name='system',
        ),
        migrations.RenameField(
            model_name='pyrotechniccatalogitem',
            old_name='system_fk',
            new_name='system',
        ),
        migrations.AlterField(
            model_name='pyrotechniccatalogitem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supervivencia.itemsystem', verbose_name='Sistema'),
        ),
    ]
