# Generated by Django 5.2.10 on 2026-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0023_remove_pyrotechniccatalogitem_system_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyrotechniccatalogitem',
            name='compatible_mediums',
            field=models.ManyToManyField(blank=True, related_name='compatible_catalog_items', to='supervivencia.survivalmedium', verbose_name='Medios asociados'),
        ),
    ]
