# Generated by Django 5.2.10 on 2026-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0024_pyrotechniccatalogitem_compatible_mediums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyrotechniccatalogitem',
            name='compatible_mediums',
        ),
        migrations.AddField(
            model_name='pyrotechniccatalogitem',
            name='compatible_medium_names',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Medios asociados'),
        ),
    ]
