# Generated by Django 5.2.10 on 2026-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0025_remove_pyrotechniccatalogitem_compatible_mediums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyrotechniccatalogitem',
            name='compatible_medium_names',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Unidades asociadas'),
        ),
    ]
