# Generated by Django 5.2.10 on 2026-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0026_alter_pyrotechniccatalogitem_compatible_medium_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyrotechniccatalogitem',
            name='alternate_nsn',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='N.S.N alternativo'),
        ),
    ]
