# Generated by Django 5.2.10 on 2026-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervivencia', '0027_pyrotechniccatalogitem_alternate_nsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyrotechniccatalogitem',
            name='alternate_nsn',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='N.S.N alternativo'),
        ),
        migrations.AlterField(
            model_name='pyrotechniccatalogitem',
            name='alternate_part_number',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Numero de parte alternativo'),
        ),
    ]
